### ISSUE TITLE
E118: Too many arguments for function: netrw#BrowseX

### ISSUE THREAD

**Issue by teoljungberg** [tpope/vim-fugitive#2441]
I can reproduce by running `:GBrowse` on e.g. plugin/fugitive.vim on:
- MacVim r182 (Vim 9.1.1887)

But not on:
- nvim v0.11.2
- vim 9.1 (bundled with macos 26.1)

I have rhubarb.vim installed alongside, and then when running `:GBrowse` with it disabled we do not get the error but:

> fugitive: no GBrowse handler installed for 'https://github.com/tpope/vim-fugitive'

**Comment by teoljungberg** [comment]
Will this be solved by https://github.com/tpope/vim-fugitive/pull/2439 ?

**Comment by pavoljuhas** [comment]
Do you have the latest fugitive?  This should have been addressed by #2409.

**Comment by teoljungberg** [comment]
@pavoljuhas - I'm on 61b51c09b7c9ce04e821f6cf76ea4f6f903e3cf4, which is after #2409.

https://github.com/tpope/vim-fugitive/compare/d3e2b58dec75fc6012fecc82ce0d33a45ed0560e~..61b51c09b7c9ce04e821f6cf76ea4f6f903e3cf4

**Comment by duarteocarmo** [comment]
Also seeing this!

**Comment by teoljungberg** [comment]
This problem persists on nvim 0.12.0, but not on vim 9.2.250

```
% vi --version | head -1
VIM - Vi IMproved 9.2 (2026 Feb 14, compiled Mar 25 2026 22:04:13)
% nvim --version | head -1
NVIM v0.12.0
```

**Comment by teoljungberg** [comment]
I can reproduce it if netrw has been loaded before trying `:GBrowse`, for both versions of vim/nvim
linked in earlier post.

Non working
```
% vim --clean --cmd 'set rtp+=~/.vim/pack/bundle/start/fugitive,~/.vim/pack/bundle/start/rhubarb' -c 'runtime! plugin/fugitive.vim' -c 'runtime! plugin/rhubarb.vim' -c 'packadd netrw' -c 'Explore .' -c 'edit vimrc' -c '1GBrowse'
```

Working
```
% vim --clean --cmd 'set rtp+=~/.vim/pack/bundle/start/fugitive,~/.vim/pack/bundle/start/rhubarb' -c 'runtime! plugin/fugitive.vim' -c 'runtime! plugin/rhubarb.vim' -c 'packadd netrw' -c 'edit vimrc' -c '1GBrowse' -c 'Explore .' -c 'edit vimrc' -c '1GBrowse'

**Comment by alexpls** [comment]
Until a proper fix gets merged in, I ended up patching this by defining my own `Browse` function which uses the `open` program (macOS) to browse to the given URL. This'll get used instead of `GBrowse` when defined:

```lua
vim.api.nvim_create_user_command("Browse", function(opts)
  vim.fn.system({ "open", opts.fargs[1] })
end, { nargs = 1 })
```

**Comment by etiennebarrie** [comment]
Still seeing this issue, I think relying on netrw#os might not be a good idea given it's internal to netrw: https://github.com/vim/vim/blob/v9.2.0475/runtime/pack/dist/opt/netrw/autoload/netrw/os.vim#L1

I've done like the previous comment and defined Browse (for Vim 9):

```vim
command! -nargs=1 Browse call dist#vim9#Open(<q-args>)
```
